# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/SoC_Fall2022/lab_7/Lab7_Serbin/vivado/SDR_Serbin.srcs/sources_1/bd/design_1/ip/design_1_radio_fifo_0_0/design_1_radio_fifo_0_0.xci
# IP: The module: 'design_1_radio_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/SoC_Fall2022/lab_7/Lab7_Serbin/vivado/SDR_Serbin.gen/sources_1/bd/design_1/ip/design_1_radio_fifo_0_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# IP: C:/SoC_Fall2022/lab_7/Lab7_Serbin/vivado/SDR_Serbin.srcs/sources_1/bd/design_1/ip/design_1_radio_fifo_0_0/design_1_radio_fifo_0_0.xci
# IP: The module: 'design_1_radio_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/SoC_Fall2022/lab_7/Lab7_Serbin/vivado/SDR_Serbin.gen/sources_1/bd/design_1/ip/design_1_radio_fifo_0_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet
